### ISSUE TITLE
nuSQUIDS constructor in python binding example

### ISSUE THREAD

**Issue by heroxbd** [arguelles/nuSQuIDS#12]
Hi,

In the [python binding example](https://github.com/arguelles/nuSQuIDS/blob/master/resources/python/example/nuSQUIDS-DEMO.ipynb), the cell
```
interactions = False
logscale = False
E_min = 1.0*units.GeV
E_max = 10.0*units.GeV
E_nodes = 101
neutrino_flavors = 3

nsq.nuSQUIDS(E_min, E_max, E_nodes, neutrino_flavors,nsq.NeutrinoType.neutrino,logscale,interactions)
```

results in a function signature mismatch error

```
ArgumentError: Python argument types in
    nuSQUIDS.__init__(nuSQUIDS, float, float, int, int, NeutrinoType, bool, bool)
did not match C++ signature:
    __init__(_object*, unsigned int numneu, nusquids::NeutrinoType NT)
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename)
    __init__(_object*, nusquids::marray<double, 1u, std::allocator<double> > E_vector, unsigned int numneu, nusquids::NeutrinoType NT, bool iinteraction, std::shared_ptr<nusquids::NeutrinoCrossSections> ncs)
    __init__(_object*, nusquids::marray<double, 1u, std::allocator<double> > E_vector, unsigned int numneu, nusquids::NeutrinoType NT, bool iinteraction)
    __init__(_object*, nusquids::marray<double, 1u, std::allocator<double> > E_vector, unsigned int numneu, nusquids::NeutrinoType NT)
    __init__(_object*, nusquids::marray<double, 1u, std::allocator<double> > E_vector, unsigned int numneu)
```

I also tried to pass a numpy array by:

```
E_vector = np.array(E_min, E_max, E_nodes)
nsq.nuSQUIDS(E_vector, neutrino_flavors,nsq.NeutrinoType.neutrino,logscale,interactions)
```
But the signture still does not match.

I looked into `resources/python/src/nuSQUIDSpy.cpp`, and there is a struct of `marray_from_python`, but I haven't figured out how to use it yet.

Any hints for initialing nuSQUIDS in the multiple energy mode?  Or is it possible to construct an `nusquids::marray<double, 1u, std::allocator<double> >`  object from numpy array?

**Comment by cnweaver** [comment]
Hi, 

I'm afraid that example is badly out of date. We are looking into modernizing it; in the meantime the thing you want is to replace several of the parameters in that constructor call (`E_min`, `E_max`, `E_nodes`, and `logscale`) with a single 1D array of energies to be used (which is much more flexible than our old approach anyway, since it allows you to choose any ordered set of energies you want, not just linear and logarithmic spacings):

`nsq.nuSQUIDS(numpy.linspace(E_min, E_max, E_nodes), neutrino_flavors,nsq.NeutrinoType.neutrino,interactions)`

Your guess was very close, you just also needed to remove the now useless `logscale`. `marray` is quite analogous to `numpy.array`, and can indeed be constructed from it. You may find the C++ headers, which have documentation comments, a better guide on how to use things than the python binding code. In general, I would encourage using the C++ interface directly; the python interface is much less capable on the whole.

**Comment by arguelles** [comment]
@heroxbd If you still have this problem, please send the issue again with the updated code version.
